import React, { createContext, useState } from 'react';

// 1. Create the Context
export const InterviewContext = createContext();

// 2. Create the Provider Component
export const InterviewProvider = ({ children }) => {
    // State to track if an API request is currently processing
    const [loading, setLoading] = useState(false);
    
    // State to store the specific interview report currently being viewed
    const [report, setReport] = useState(null);
    
    // State to store the array of all past interview reports generated by the user
    const [reports, setReports] = useState([]);

    return (
        <InterviewContext.Provider 
            value={{ 
                loading, 
                setLoading, 
                report, 
                setReport, 
                reports, 
                setReports 
            }}
        >
            {children}
        </InterviewContext.Provider>
    );
};