const express = require('express');
const interviewRouter = express.Router();

// Middlewares
const authMiddleware = require('../middlewares/auth.middleware.js');
const upload = require('../middlewares/file.middleware.js');

// Controller
const interviewController = require('../controllers/interview.controller.js');

/**
 * @route POST /api/interview/generate
 * @desc Generate a new interview report based on resume PDF, self description, and job description
 * @access Private
 */
// 🚨 SAFELY UPDATED: Changed from '/' to '/generate'
interviewRouter.post(
    '/generate', 
    authMiddleware.authUser, 
    upload.single('resume'), 
    interviewController.generateInterviewReportController
);

/**
 * @route GET /api/interview/:interviewId
 * @desc Get a specific interview report by its ID
 * @access Private
 */
// Unchanged - This route was already working perfectly!
interviewRouter.get(
    '/:interviewId', 
    authMiddleware.authUser, 
    interviewController.getInterviewReportByIdController
);

/**
 * @route GET /api/interview/all
 * @desc Fetch all interview reports generated by the logged-in user
 * @access Private
 */
// 🚨 SAFELY UPDATED: Changed from '/' to '/all'
interviewRouter.get(
    '/all', 
    authMiddleware.authUser, 
    interviewController.getAllInterviewReportsController
);

module.exports = interviewRouter;