import axios from 'axios';

const api = axios.create({
    baseURL: import.meta.env.VITE_API_BASE_URL || 'http://localhost:3000', 
    withCredentials: true 
});

/**
 * Service to generate an interview report based on self description, resume, and job description.
 */
export const generateInterviewReport = async (jobDescription, selfDescription, resumeFile) => {
    try {
        const formData = new FormData();
        formData.append('jobDescription', jobDescription || '');
        formData.append('selfDescription', selfDescription || '');

        if (resumeFile) {
            const actualFile = resumeFile instanceof FileList ? resumeFile[0] : resumeFile;
            if (actualFile) {
                formData.append('resume', actualFile); 
            }
        }

        // 🚨 SAFELY UPDATED: explicitly calling '/api/interview/generate'
        const response = await api.post('/api/interview/generate', formData);
        return response.data;
        
    } catch (error) {
        console.error("API Error in generateInterviewReport:", error);
        throw error; 
    }
};

/**
 * Service to get a specific interview report by its ID.
 */
export const getInterviewReportById = async (interviewId) => {
    try {
        const response = await api.get(`/api/interview/${interviewId}`);
        return response.data;
    } catch (error) {
        console.error("API Error in getInterviewReportById:", error);
        throw error;
    }
};

/**
 * Service to get all interview reports generated by the logged-in user.
 */
export const getAllInterviewReports = async () => {
    try {
        // 🚨 SAFELY UPDATED: explicitly calling '/api/interview/all'
        const response = await api.get('/api/interview/all');
        return response.data;
    } catch (error) {
        console.error("API Error in getAllInterviewReports:", error);
        throw error;
    }
};