import axios from 'axios';

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:3000/api';

// 1. Create an Axios instance with the base URL and credentials
const api = axios.create({
    baseURL: `${API_BASE_URL}/interview`, 
    withCredentials: true // Ensures cookies (like the JWT token) are sent with every request
});

/**
 * Service to generate an interview report based on self description, resume, and job description.
 */
export const generateInterviewReport = async (jobDescription, selfDescription, resumeFile) => {
    try {
        const formData = new FormData();
        
        // SAFEY CHECK 1: Prevent sending the literal string "undefined" to the backend
        formData.append('jobDescription', jobDescription || '');
        formData.append('selfDescription', selfDescription || '');

        // SAFETY CHECK 2: The "Smoking Gun" Fix
        // Ensure we are sending a single, physical File object, NOT a FileList array
        if (resumeFile) {
            const actualFile = resumeFile instanceof FileList ? resumeFile[0] : resumeFile;
            
            if (actualFile) {
                formData.append('resume', actualFile); 
            }
        }

        const response = await api.post('/', formData);
        return response.data;
        
    } catch (error) {
        console.error("API Error in generateInterviewReport:", error);
        throw error; // We MUST throw the error so your UI loader knows to stop spinning!
    }
};

/**
 * Service to get a specific interview report by its ID.
 */
export const getInterviewReportById = async (interviewId) => {
    try {
        const response = await api.get(`/${interviewId}`);
        return response.data;
    } catch (error) {
        console.error("API Error in getInterviewReportById:", error);
        throw error;
    }
};

/**
 * Service to get all interview reports generated by the logged-in user.
 */
export const getAllInterviewReports = async () => {
    try {
        const response = await api.get('/');
        return response.data;
    } catch (error) {
        console.error("API Error in getAllInterviewReports:", error);
        throw error;
    }
};